import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
  ManyToOne,
  JoinColumn,
} from "typeorm";
import { Term } from "./Term";

/**
 * ScheduleTemplate - Pre-computed schedules for specific preference combinations
 * 
 * HIERARCHICAL TEMPLATE SYSTEM:
 * - PARENT TEMPLATE: Contains ALL combinations for (term, system, electives) - NO excluded core courses
 *   - Generated by admin OR student's first request
 *   - parent_hash = hash(term, system, electives) - excludedCore is EMPTY
 *   - parent_template_id = NULL (it's the parent)
 * 
 * - CHILD TEMPLATE: Derived from parent by filtering out excluded core courses
 *   - Generated when student excludes core courses
 *   - child_hash = hash(term, system, electives, excludedCore)
 *   - parent_template_id = parent's ID
 *   - Schedules are FILTERED from parent (not regenerated)
 * 
 * LOOKUP STRATEGY:
 * 1. If excludedCore is empty → Use parent template directly
 * 2. If excludedCore exists → Look for child template with matching hash
 *    - If child exists → Use child template
 *    - If child NOT exists → Find parent → Filter → Save as new child
 * 
 * BACKWARD COMPATIBILITY: Old templates still work via elective_combination_hash
 */
@Entity("schedule_templates")
@Index(["preferences_hash"], { unique: true }) // PRIMARY lookup key for new system
@Index(["parent_hash"]) // Index for finding parent templates
@Index(["parent_template_id"]) // Index for finding child templates of a parent
@Index(["term_id", "system_type", "elective_combination_hash"], { unique: true }) // For backward compatibility
@Index(["term_id"]) // Individual index for faster lookups
@Index(["system_type"]) // Individual index for faster lookups
@Index(["elective_combination_hash"]) // Individual index for faster lookups (backward compatibility)
export class ScheduleTemplate {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ type: "varchar", length: 255, nullable: true, unique: true })
  preferences_hash!: string | null; // Hash including excludedCore (for child lookup)
  
  @Column({ type: "varchar", length: 255, nullable: true })
  parent_hash!: string | null; // Hash WITHOUT excludedCore (for parent lookup) - same as preferences_hash for parent templates
  
  @Column({ type: "int", nullable: true })
  parent_template_id!: number | null; // NULL for parent templates, points to parent ID for child templates
  
  @Column({ type: "boolean", default: false })
  is_parent!: boolean; // TRUE for parent templates (all combinations), FALSE for child templates (filtered)

  @Column({ type: "int" })
  term_id!: number;

  @ManyToOne(() => Term)
  @JoinColumn({ name: "term_id" })
  term!: Term;

  @Column({ type: "int" })
  system_type!: number; // 140, 160, or 180

  @Column({ type: "text", nullable: true })
  elective_course_ids!: string | null; // JSON array of elective course IDs (sorted), null if core-only

  @Column({ type: "varchar", length: 255, nullable: true })
  elective_combination_hash!: string | null; // MD5 hash of sorted elective IDs (for backward compatibility)

  @Column({ type: "text", nullable: true })
  excluded_days!: string | null; // JSON array of excluded days (for reference)

  @Column({ type: "text", nullable: true })
  excluded_core_course_ids!: string | null; // JSON array of excluded core course IDs (for reference)

  @Column({ type: "text", nullable: true })
  preferred_instructors!: string | null; // JSON array of preferred instructors (for reference)

  @Column({ type: "varchar", length: 20, nullable: true })
  campus_track!: string | null; // "northampton" or "normal" for Term 4 System 140 only (NORTHAMPTON class separation)

  @Column({ type: "jsonb" })
  base_schedules!: any; // Array of pre-computed schedules (already filtered with preferences applied)

  @Column({ type: "int", default: 0 })
  schedule_count!: number; // Number of schedules in base_schedules

  @Column({ type: "int", default: 0 })
  access_count!: number; // Track how many times this template was used

  @Column({ type: "timestamp", nullable: true })
  last_accessed_at!: Date | null; // Last time this template was accessed

  @Column({ type: "boolean", default: false })
  is_generating!: boolean; // True while schedules are being generated (for reservation pattern)

  @CreateDateColumn({ type: "timestamp" })
  createdAt!: Date;

  @UpdateDateColumn({ type: "timestamp" })
  updatedAt!: Date;
}
