/**
 * Unified Preferences Hash Utility
 * 
 * HIERARCHICAL TEMPLATE SYSTEM:
 * 
 * PARENT TEMPLATE (all combinations):
 * - parent_hash = hash(term, system, electives) - excludedCore is EMPTY
 * - Contains ALL valid schedule combinations
 * - Generated by admin OR student's first request
 * 
 * CHILD TEMPLATE (filtered):
 * - child_hash = hash(term, system, electives, excludedCore)
 * - Contains schedules FILTERED from parent (courses containing excludedCore removed)
 * - Generated when student excludes core courses
 * - Stores parent_template_id for reference
 * 
 * RUNTIME FILTERS (NOT in hash):
 * - excludedDays → Scoring penalty (not hard filter)
 * - preferredInstructors → Scoring bonus (not hard filter)
 */

import * as crypto from "crypto";

export interface SchedulePreferences {
  termId: number;
  systemType: number;
  electiveCourseIds?: number[] | null;
  excludedDays?: string[] | null;
  excludedCoreCourseIds?: number[] | null;
  preferredInstructors?: string[] | null;
  campusTrack?: "northampton" | "normal" | null; // For Term 4 System 140 only: separates NORTHAMPTON classes from normal classes
  /** Sorted list of class_course IDs that are closed for this term; included in hash so templates are unique per closure state. */
  closedClassCourseIds?: number[] | null;
}

/**
 * Check if campus track separation is required for given term and system
 * Only Term 4 (term_number = "4") with System 140 requires this separation
 */
export function requiresCampusTrackSeparation(termNumber: number | string, systemType: number): boolean {
  const termNum = typeof termNumber === "string" ? parseInt(termNumber) : termNumber;
  return termNum === 4 && systemType === 140;
}

/**
 * Check if a class is a NORTHAMPTON class based on its class_code
 * NORTHAMPTON classes have "NORTHAMPTON" in their name (case-insensitive)
 */
export function isNorthamptonClass(classCode: string): boolean {
  return classCode.toUpperCase().includes("NORTHAMPTON");
}

/**
 * Generate PARENT template hash (ALL combinations, NO excluded core courses)
 * This is the "master" template that contains all valid schedule combinations
 * 
 * Includes: term_id, system_type, elective_course_ids
 * Excludes: excludedCoreCourseIds (parent has ALL courses)
 * 
 * @param preferences - The schedule preferences object
 * @returns MD5 hash string (32 characters)
 */
export function generateParentTemplateHash(preferences: SchedulePreferences): string {
  // Normalize and sort elective IDs for consistent hashing
  const sortedElectiveIds = preferences.electiveCourseIds 
    ? [...preferences.electiveCourseIds].sort((a, b) => a - b)
    : [];
  
  // Parent hash does NOT include excludedCoreCourseIds (parent has all courses)
  // Format: PARENT|termId|systemType|electiveIds[|campusTrack][|closedClassCourseIds]
  const sortedClosedClassCourseIds = preferences.closedClassCourseIds
    ? [...preferences.closedClassCourseIds].sort((a, b) => a - b)
    : [];

  const hashParts = [
    "PARENT", // Prefix to distinguish from child hashes
    String(preferences.termId),
    String(preferences.systemType),
    sortedElectiveIds.length > 0 ? JSON.stringify(sortedElectiveIds) : "[]",
  ];

  // Include campusTrack in hash for Term 4 System 140 (NORTHAMPTON separation)
  if (preferences.campusTrack) {
    hashParts.push(preferences.campusTrack);
  }
  // Include closed class-course IDs so templates are unique when admin closes assigned courses
  if (sortedClosedClassCourseIds.length > 0) {
    hashParts.push(JSON.stringify(sortedClosedClassCourseIds));
  }
  
  const hashString = hashParts.join("|");
  
  // Generate MD5 hash
  const hash = crypto.createHash("md5").update(hashString).digest("hex");
  
  return hash;
}

/**
 * Generate CHILD template hash (filtered by excluded core courses)
 * This is derived from parent by filtering out excluded courses
 * 
 * Includes: term_id, system_type, elective_course_ids, excluded_core_course_ids
 * 
 * @param preferences - The schedule preferences object
 * @returns MD5 hash string (32 characters)
 */
export function generateChildTemplateHash(preferences: SchedulePreferences): string {
  // Normalize and sort elective IDs for consistent hashing
  const sortedElectiveIds = preferences.electiveCourseIds 
    ? [...preferences.electiveCourseIds].sort((a, b) => a - b)
    : [];
  
  // Normalize and sort excluded core course IDs
  const sortedExcludedCoreIds = preferences.excludedCoreCourseIds 
    ? [...preferences.excludedCoreCourseIds].sort((a, b) => a - b)
    : [];
  
  // Child hash includes excludedCoreCourseIds
  // Format: CHILD|termId|systemType|electiveIds|excludedCoreIds[|campusTrack][|closedClassCourseIds]
  const sortedClosedClassCourseIds = preferences.closedClassCourseIds
    ? [...preferences.closedClassCourseIds].sort((a, b) => a - b)
    : [];

  const hashParts = [
    "CHILD", // Prefix to distinguish from parent hashes
    String(preferences.termId),
    String(preferences.systemType),
    sortedElectiveIds.length > 0 ? JSON.stringify(sortedElectiveIds) : "[]",
    sortedExcludedCoreIds.length > 0 ? JSON.stringify(sortedExcludedCoreIds) : "[]",
  ];

  // Include campusTrack in hash for Term 4 System 140 (NORTHAMPTON separation)
  if (preferences.campusTrack) {
    hashParts.push(preferences.campusTrack);
  }
  // Include closed class-course IDs so templates are unique when admin closes assigned courses
  if (sortedClosedClassCourseIds.length > 0) {
    hashParts.push(JSON.stringify(sortedClosedClassCourseIds));
  }
  
  const hashString = hashParts.join("|");
  
  // Generate MD5 hash
  const hash = crypto.createHash("md5").update(hashString).digest("hex");
  
  return hash;
}

/**
 * Generate a BASE hash for schedule templates (LEGACY - kept for backward compatibility)
 * Use generateParentTemplateHash or generateChildTemplateHash for new code
 * 
 * Includes: term_id, system_type, elective_course_ids, excluded_core_course_ids
 * 
 * NOTE: Excluded CORE courses are in hash because they change which courses are generated
 *       Excluded DAYS are NOT in hash because they're scoring penalties, not hard filters
 *       Preferred INSTRUCTORS are NOT in hash because they're scoring bonuses only
 * 
 * @param preferences - The schedule preferences object
 * @returns MD5 hash string (32 characters)
 */
export function generateBaseTemplateHash(preferences: SchedulePreferences): string {
  // If no excluded core courses, return parent hash
  if (!preferences.excludedCoreCourseIds || preferences.excludedCoreCourseIds.length === 0) {
    return generateParentTemplateHash(preferences);
  }
  // Otherwise, return child hash
  return generateChildTemplateHash(preferences);
}

/**
 * Generate a unified hash for schedule preferences (LEGACY - kept for backward compatibility)
 * This hash includes ALL preferences - used for old templates
 * 
 * @param preferences - The schedule preferences object
 * @returns MD5 hash string (32 characters)
 */
export function generatePreferencesHash(preferences: SchedulePreferences): string {
  // Normalize and sort all arrays for consistent hashing
  const sortedElectiveIds = preferences.electiveCourseIds 
    ? [...preferences.electiveCourseIds].sort((a, b) => a - b)
    : [];
  
  const sortedExcludedDays = preferences.excludedDays 
    ? [...preferences.excludedDays].sort()
    : [];
  
  const sortedExcludedCoreIds = preferences.excludedCoreCourseIds 
    ? [...preferences.excludedCoreCourseIds].sort((a, b) => a - b)
    : [];
  
  // Normalize instructors: trim, lowercase, then sort
  const normalizedInstructors = preferences.preferredInstructors
    ? preferences.preferredInstructors
        .map(inst => inst.trim().toLowerCase())
        .filter(inst => inst.length > 0)
        .sort()
    : [];
  
  // Create a deterministic string representation
  // Format: termId|systemType|electiveIds|excludedDays|excludedCoreIds|instructors
  const hashParts = [
    String(preferences.termId),
    String(preferences.systemType),
    sortedElectiveIds.length > 0 ? JSON.stringify(sortedElectiveIds) : "[]",
    sortedExcludedDays.length > 0 ? JSON.stringify(sortedExcludedDays) : "[]",
    sortedExcludedCoreIds.length > 0 ? JSON.stringify(sortedExcludedCoreIds) : "[]",
    normalizedInstructors.length > 0 ? JSON.stringify(normalizedInstructors) : "[]",
  ];
  
  const hashString = hashParts.join("|");
  
  // Generate MD5 hash
  const hash = crypto.createHash("md5").update(hashString).digest("hex");
  
  return hash;
}

/**
 * Parse preferences from request body (for student requests)
 */
export function parsePreferencesFromRequest(body: any): SchedulePreferences {
  return {
    termId: body.termId,
    systemType: body.systemType || body.scheduleSystemType,
    electiveCourseIds: body.electiveCourseIds || null,
    excludedDays: body.excludedDays || [],
    excludedCoreCourseIds: body.excludedCoreCourseIds || null,
    preferredInstructors: body.preferredInstructors || [],
    campusTrack: body.campusTrack || null, // "northampton" or "normal" for Term 4 System 140
    // closedClassCourseIds is set server-side from DB for the term, not from request body
  };
}

/**
 * Schedule with full metadata for filtering
 */
export interface ScheduleWithMetadata {
  days: string[];
  totalDays: number;
  gaps: number;
  instructors: { [courseCode: string]: string };
  courseIds: number[];
  score: number;
  excludedDaysUsed?: number;
  preferredCoursesCount?: number;
  sessions: any[];
  [key: string]: any; // Allow other properties
}

/**
 * Calculate excluded days count for a schedule
 * Does NOT filter - just calculates how many excluded days are used
 * This matches the original behavior which scored penalties, not filtered
 * 
 * @param schedule - Schedule with metadata
 * @param excludedDays - Array of day names to exclude
 * @returns Number of excluded days used in this schedule
 */
export function calculateExcludedDaysUsed(
  schedule: ScheduleWithMetadata,
  excludedDays: string[] | null | undefined
): number {
  if (!excludedDays || excludedDays.length === 0) {
    return 0;
  }
  
  const excludedSet = new Set(excludedDays.map(d => d.toLowerCase()));
  const scheduleDays = schedule.days || [];
  
  let count = 0;
  for (const day of scheduleDays) {
    if (excludedSet.has(day.toLowerCase())) {
      count++;
    }
  }
  return count;
}

/**
 * Filter schedules by excluded core courses
 * Removes schedules that contain any excluded core course
 * 
 * @param schedules - Array of schedules with metadata
 * @param excludedCoreCourseIds - Array of course IDs to exclude
 * @returns Filtered array of schedules
 */
export function filterByExcludedCoreCourses(
  schedules: ScheduleWithMetadata[],
  excludedCoreCourseIds: number[] | null | undefined
): ScheduleWithMetadata[] {
  if (!excludedCoreCourseIds || excludedCoreCourseIds.length === 0) {
    return schedules;
  }
  
  const excludedSet = new Set(excludedCoreCourseIds);
  
  return schedules.filter(schedule => {
    // Check if any of the schedule's courses are in the excluded set
    const scheduleCourseIds = schedule.courseIds || [];
    for (const courseId of scheduleCourseIds) {
      if (excludedSet.has(courseId)) {
        return false; // Exclude this schedule
      }
    }
    return true; // Keep this schedule
  });
}

/**
 * Derive a CHILD template from a PARENT template by removing excluded core course sessions
 * This is the key function that enables the hierarchical template system
 * 
 * Process:
 * 1. Takes parent's base_schedules (ALL combinations)
 * 2. For each schedule, REMOVES the L, S, LB sessions of excluded core courses
 * 3. Recalculates days, gaps, totalDays for the modified schedule
 * 4. Re-sorts schedules by the new metrics
 * 5. Returns modified schedules for the child template
 * 
 * NOTE: This does NOT remove entire schedules - it removes specific course sessions
 * 
 * @param parentSchedules - Array of schedules from parent template (ALL combinations)
 * @param excludedCoreCourseIds - Array of core course IDs to exclude
 * @returns Modified array of schedules with excluded course sessions removed
 */
export function deriveChildTemplateFromParent(
  parentSchedules: ScheduleWithMetadata[],
  excludedCoreCourseIds: number[]
): ScheduleWithMetadata[] {
  console.log(`[deriveChildTemplateFromParent] Deriving child template from ${parentSchedules.length} parent schedules`);
  console.log(`[deriveChildTemplateFromParent] Removing sessions for core courses: ${excludedCoreCourseIds.join(", ")}`);
  
  const excludedSet = new Set(excludedCoreCourseIds);
  
  // Process each schedule - remove excluded course sessions and recalculate
  const modifiedSchedules = parentSchedules.map(schedule => {
    // Clone the schedule
    const newSchedule = { ...schedule };
    
    // Filter sessions - remove sessions for excluded courses
    const originalSessions = schedule.sessions || [];
    const filteredSessions = originalSessions.filter((session: any) => {
      // Check if this session belongs to an excluded course
      const courseId = session.course?.id || session.courseId;
      return !excludedSet.has(courseId);
    });
    
    // If no sessions were removed, return original schedule
    if (filteredSessions.length === originalSessions.length) {
      return schedule;
    }
    
    // Update sessions
    newSchedule.sessions = filteredSessions;
    
    // Recalculate days from remaining sessions
    const daysSet = new Set<string>();
    const daySlots = new Map<string, number[]>();
    
    filteredSessions.forEach((session: any) => {
      const day = String(session.day);
      daysSet.add(day);
      
      if (!daySlots.has(day)) {
        daySlots.set(day, []);
      }
      daySlots.get(day)!.push(Number(session.slot));
    });
    
    newSchedule.days = Array.from(daysSet).sort();
    newSchedule.totalDays = daysSet.size;
    
    // Recalculate gaps
    let totalGaps = 0;
    daySlots.forEach((slots, day) => {
      if (slots.length > 1) {
        const sortedSlots = [...slots].sort((a, b) => a - b);
        for (let i = 1; i < sortedSlots.length; i++) {
          const gap = sortedSlots[i] - sortedSlots[i - 1] - 1;
          if (gap > 0) {
            totalGaps += gap;
          }
        }
      }
    });
    newSchedule.gaps = totalGaps;
    
    // Update courseIds - remove excluded courses
    const originalCourseIds = schedule.courseIds || [];
    newSchedule.courseIds = originalCourseIds.filter((id: number) => !excludedSet.has(id));
    
    // Update instructors map - remove excluded courses
    if (schedule.instructors) {
      const newInstructors: { [key: string]: string } = {};
      for (const [courseCode, instructor] of Object.entries(schedule.instructors)) {
        // Keep if not in excluded set (we check by courseId in sessions)
        const courseSession = originalSessions.find((s: any) => 
          (s.course?.code === courseCode || s.courseCode === courseCode) && 
          excludedSet.has(s.course?.id || s.courseId)
        );
        if (!courseSession) {
          newInstructors[courseCode] = instructor as string;
        }
      }
      newSchedule.instructors = newInstructors;
    }
    
    // Update courses array if present
    if (schedule.courses) {
      newSchedule.courses = schedule.courses.filter((c: any) => 
        !excludedSet.has(c.course?.id || c.id)
      );
    }
    
    // Recalculate score (simplified - same formula as buildSchedule)
    const baseScore = 1000000000;
    const daysBonus = (7 - newSchedule.totalDays) * 1000000;
    const gapsPenalty = totalGaps * 10000;
    newSchedule.score = baseScore + daysBonus - gapsPenalty;
    
    return newSchedule;
  });
  
  // Remove duplicate schedules (same combination after removing courses)
  // Use a hash of remaining course-class combinations
  const seen = new Set<string>();
  const uniqueSchedules = modifiedSchedules.filter(schedule => {
    // Create a unique key based on remaining sessions
    const key = (schedule.sessions || [])
      .map((s: any) => `${s.course?.id || s.courseId}_${s.class?.id || s.classId}_${s.day}_${s.slot}`)
      .sort()
      .join('|');
    
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
  
  // Sort by score (descending), then by days (ascending), then by gaps (ascending)
  uniqueSchedules.sort((a, b) => {
    // Primary: fewer days is better
    if (a.totalDays !== b.totalDays) {
      return a.totalDays - b.totalDays;
    }
    // Secondary: fewer gaps is better
    if (a.gaps !== b.gaps) {
      return a.gaps - b.gaps;
    }
    // Tertiary: higher score is better
    return b.score - a.score;
  });
  
  const removedSessions = parentSchedules.reduce((total, s) => {
    const original = (s.sessions || []).length;
    const modified = (modifiedSchedules.find(m => m === s) || { sessions: [] }).sessions?.length || 0;
    return total + (original - modified);
  }, 0);
  
  console.log(`[deriveChildTemplateFromParent] Modified ${modifiedSchedules.length} schedules`);
  console.log(`[deriveChildTemplateFromParent] Unique schedules after dedup: ${uniqueSchedules.length}`);
  console.log(`[deriveChildTemplateFromParent] Removed sessions from excluded courses, recalculated days/gaps, sorted by quality`);
  
  return uniqueSchedules;
}

/**
 * Check if a template request should use parent template or needs a child template
 * 
 * @param preferences - The schedule preferences object
 * @returns { needsChild: boolean, parentHash: string, childHash?: string }
 */
export function analyzeTemplateRequest(preferences: SchedulePreferences): {
  needsChild: boolean;
  parentHash: string;
  childHash: string | null;
} {
  const parentHash = generateParentTemplateHash(preferences);
  
  // If no excluded core courses, use parent directly
  if (!preferences.excludedCoreCourseIds || preferences.excludedCoreCourseIds.length === 0) {
    return {
      needsChild: false,
      parentHash,
      childHash: null,
    };
  }
  
  // If excluded core courses exist, we need a child template
  const childHash = generateChildTemplateHash(preferences);
  return {
    needsChild: true,
    parentHash,
    childHash,
  };
}

/**
 * Generate a unique elective_combination_hash for CHILD templates
 * Includes both elective IDs AND excluded core course IDs to ensure uniqueness
 * 
 * This is needed because the database has a unique constraint on 
 * (term_id, system_type, elective_combination_hash) which would conflict
 * between parent and child templates if we use the same hash
 * 
 * @param electiveCourseIds - Array of elective course IDs
 * @param excludedCoreCourseIds - Array of excluded core course IDs
 * @returns MD5 hash string (32 characters)
 */
export function generateChildElectiveCombinationHash(
  electiveCourseIds: number[] | null | undefined,
  excludedCoreCourseIds: number[] | null | undefined
): string {
  // Sort for consistent hashing
  const sortedElectiveIds = electiveCourseIds 
    ? [...electiveCourseIds].sort((a, b) => a - b)
    : [];
  
  const sortedExcludedCoreIds = excludedCoreCourseIds 
    ? [...excludedCoreCourseIds].sort((a, b) => a - b)
    : [];
  
  // Combine electives and excluded core into unique string
  // Format: CHILD_ELECTIVES|electiveIds|excludedCoreIds
  const hashParts = [
    "CHILD_ELECTIVES",
    sortedElectiveIds.length > 0 ? JSON.stringify(sortedElectiveIds) : "[]",
    sortedExcludedCoreIds.length > 0 ? JSON.stringify(sortedExcludedCoreIds) : "[]",
  ];
  
  const hashString = hashParts.join("|");
  
  return crypto.createHash("md5").update(hashString).digest("hex");
}

/**
 * Re-score schedules with SAME scoring formula as generation time
 * This recalculates excludedDaysUsed and applies identical penalties/bonuses
 * 
 * CRITICAL: This must match the scoring in buildSchedule() exactly!
 * - baseScore = 1,000,000,000
 * - excludedDaysScore = 500,000,000 if 0, else -(500,000,000 * count)
 * - daysBonus = (7 - totalDays) * 1,000,000
 * - gapsPenalty = gaps * 10,000
 * - preferredInstructorsBonus = 50,000,000 per course
 * 
 * @param schedules - Array of schedules with metadata
 * @param preferredInstructors - Array of preferred instructor names
 * @param excludedDays - Array of excluded days (for scoring penalty)
 * @returns Schedules with updated scores (identical to original algorithm)
 */
export function rescoreWithPreferences(
  schedules: ScheduleWithMetadata[],
  preferredInstructors: string[] | null | undefined,
  excludedDays: string[] | null | undefined
): ScheduleWithMetadata[] {
  // Normalize preferred instructors
  const normalizedPreferred = preferredInstructors
    ? preferredInstructors.map(name => name.trim().toLowerCase())
    : [];
  
  return schedules.map(schedule => {
    // Base score (SAME as buildSchedule)
    const baseScore = 1000000000;
    
    // RECALCULATE excludedDaysUsed at request time (not using stored value!)
    // This is critical because base schedules were generated without excluded days
    const excludedDaysUsed = calculateExcludedDaysUsed(schedule, excludedDays);
    
    // Excluded days score (SAME formula as buildSchedule)
    // +500M if zero excluded days, -500M per excluded day otherwise
    const excludedDaysScore = excludedDaysUsed === 0 ? 500000000 : -(500000000 * excludedDaysUsed);
    
    // Days bonus (SAME as buildSchedule) - fewer days = better
    const totalDays = schedule.totalDays || schedule.days?.length || 5;
    const daysBonus = (7 - totalDays) * 1000000;
    
    // Gaps penalty (SAME as buildSchedule)
    const gaps = schedule.gaps || 0;
    const gapsPenalty = gaps * 10000;
    
    // Preferred instructors bonus (SAME as buildSchedule - 50M per course)
    let preferredInstructorsBonus = 0;
    let preferredCoursesCount = 0;
    
    if (normalizedPreferred.length > 0 && schedule.instructors) {
      for (const [courseCode, instructorName] of Object.entries(schedule.instructors)) {
        if (instructorName && normalizedPreferred.includes(instructorName.toLowerCase().trim())) {
          preferredInstructorsBonus += 100000000; // 100 MILLION per course - HIGHEST priority
          preferredCoursesCount++;
        }
      }
    }
    
    // Calculate final score (IDENTICAL formula to buildSchedule)
    const newScore = baseScore + excludedDaysScore + daysBonus - gapsPenalty + preferredInstructorsBonus;
    
    return {
      ...schedule,
      score: newScore,
      excludedDaysUsed: excludedDaysUsed,
      preferredCoursesCount: preferredCoursesCount,
    };
  });
}

/**
 * Sort schedules by score (descending) and return top N
 * Uses same sorting criteria as generation
 * 
 * @param schedules - Array of schedules with scores
 * @param limit - Maximum number of schedules to return
 * @returns Top N schedules sorted by score
 */
export function sortAndLimitSchedules(
  schedules: ScheduleWithMetadata[],
  limit: number = 100
): ScheduleWithMetadata[] {
  // Sort by score descending, then by preferred courses count descending
  const sorted = [...schedules].sort((a, b) => {
    // Primary: score (higher is better)
    if (b.score !== a.score) {
      return b.score - a.score;
    }
    // Secondary: preferred courses count (higher is better)
    const aPreferred = a.preferredCoursesCount || 0;
    const bPreferred = b.preferredCoursesCount || 0;
    if (bPreferred !== aPreferred) {
      return bPreferred - aPreferred;
    }
    // Tertiary: fewer days is better
    const aDays = a.totalDays || a.days?.length || 5;
    const bDays = b.totalDays || b.days?.length || 5;
    if (aDays !== bDays) {
      return aDays - bDays;
    }
    // Quaternary: fewer gaps is better
    return (a.gaps || 0) - (b.gaps || 0);
  });
  
  return sorted.slice(0, limit);
}

/**
 * Apply re-scoring to schedules (no hard filters needed!)
 * This is the main function called at request time
 * 
 * IMPORTANT: 
 * - Excluded CORE COURSES are handled at GENERATION time (in the hash)
 * - Excluded DAYS receive scoring penalties (not filtered out)
 * - Preferred INSTRUCTORS receive scoring bonuses
 * 
 * This matches the original behavior exactly!
 * 
 * @param schedules - Pre-generated schedules with metadata
 * @param excludedDays - Days to penalize (NOT filter)
 * @param excludedCoreCourseIds - UNUSED (now in hash, handled at generation)
 * @param preferredInstructors - Preferred instructors for bonus
 * @param limit - Max schedules to return
 * @returns Re-scored, sorted, and limited schedules
 */
export function applyFiltersAndRescore(
  schedules: ScheduleWithMetadata[],
  excludedDays: string[] | null | undefined,
  excludedCoreCourseIds: number[] | null | undefined, // Kept for API compatibility but unused
  preferredInstructors: string[] | null | undefined,
  limit: number = 100
): ScheduleWithMetadata[] {
  console.log(`[applyFiltersAndRescore] Starting with ${schedules.length} schedules`);
  
  // NOTE: excludedCoreCourseIds is now handled at GENERATION time (in the hash)
  // So all schedules in the template already exclude those core courses
  // No filtering needed here!
  
  // Re-score with excluded days penalties and preferred instructors bonus
  // This recalculates excludedDaysUsed and applies SAME penalties as original algorithm
  const rescored = rescoreWithPreferences(schedules, preferredInstructors, excludedDays);
  console.log(`[applyFiltersAndRescore] Re-scored ${rescored.length} schedules with excluded days penalty + instructor bonus`);
  
  // Sort and limit
  const result = sortAndLimitSchedules(rescored, limit);
  console.log(`[applyFiltersAndRescore] Returning ${result.length} schedules`);
  
  return result;
}
